package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Перекресток")
    void generatedTest() {
        step("Открыть https://www.perekrestok.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("Навести курсор на кнопку \"Каталог\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Выбрать раздел \"Рыба\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Найти товар, содержащий текст \"мидии новый океан\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что цена товара \"144,99\"", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.perekrestok.ru/'", () ->
            open("https://www.perekrestok.ru/"));

        step("Page title should have text 'Request Rejected'", () -> {
            String expectedTitle = "Request Rejected";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.perekrestok.ru/'", () ->
            open("https://www.perekrestok.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}